### ISSUE TITLE
Detail how to hook up relay

### ISSUE THREAD

**Issue by challgren** [3DCoded/3dchameleon-klipper#1]
I was reading the docs and I can't understand how to hook up the limit switch to the relay. Can you detail this or provide a photo?

Thanks!

**Comment by challgren** [comment]
After reading the 3d chameleon forums you can directly hook up to the raspberry pi by inverting the pin and connecting green to your gpio and black to a ground. 2.0v+ will trigger the chameleon. But thank you for the guide.

**Comment by 3DCoded** [comment]
Thank you. I didn't see that. I will experiment with that to see if any changes would need to be made to the plugin/documentation.

**Comment by challgren** [comment]
The biggest would be inversion of the pin. I was using your script and the dependency on the filament sensor is kind of a deal breaker right now. Also having a lot of config file parsing issues.

**Comment by 3DCoded** [comment]
I have updated the documentation (the Wiki) on how to invert the pin, but the filament sensor is needed for reliability reasons. What kind of config file parsing issues are you running into? Can you post your error messages here?

**Comment by 3DCoded** [comment]
I can add support for not using a filament sensor, but that would reduce the reliability of the system.

**Comment by 3DCoded** [comment]
I just added experimental support for disabling the filament sensor, which can be used by setting `filament_sensor_name: disabled`.
